FROM mcr.microsoft.com/devcontainers/base:bullseye

# Install php-fpm
RUN curl -sS https://packages.sury.org/php/apt.gpg | apt-key add - \
    && echo "deb https://packages.sury.org/php/ bullseye main" | tee /etc/apt/sources.list.d/php.list

RUN apt-get update && apt-get install -y \
    libzip-dev \
    git \
    unzip \
    wget \
    libfreetype6-dev \
    libicu-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libxslt1-dev \
    mariadb-client \
    sendmail-bin \
    sendmail \
    sudo \
    redis \
    vim \
    curl \
    libzip-dev \
    unzip \
    wget \
    libmagickwand-dev \
    imagemagick \
    libjpeg-dev \
    \
    php8.3-fpm \
    php8.3-zip \
    php8.3-simplexml \
    php8.3-curl \
    php8.3-intl \
    php8.3-soap \
    php8.3-bcmath \
    php8.3-gd \
    php8.3-mysql \
    php8.3-mbstring \
    php8.3-swoole \
    php8.3-xdebug \
    \
    libnss3-tools\
    inotify-tools \
    \
    && apt clean

# configure php
RUN echo 'memory_limit = 2G' >> /etc/php/8.3/fpm/php.ini
RUN echo 'max_input_vars = 10000' >> /etc/php/8.3/fpm/php.ini
RUN echo 'memory_limit = -1' >> /etc/php/8.3/fpm/conf.d/memory_limit.ini

RUN echo 'memory_limit = 2G' >> /etc/php/8.3/cli/php.ini
RUN echo 'max_input_vars = 10000' >> /etc/php/8.3/cli/php.ini
RUN echo 'memory_limit = -1' >> /etc/php/8.3/cli/conf.d/memory_limit.ini

RUN mkdir -p /run/php

COPY conf/php-fpm/fpm-pool.conf /etc/php/8.3/fpm/pool.d/www.conf

RUN ln -s /usr/sbin/php-fpm8.3 /usr/sbin/php-fpm

# install mkcert
RUN curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
RUN chmod +x mkcert-v*-linux-amd64
RUN sudo cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert

# composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer --version

# n98-magerun2
RUN curl -o /usr/local/bin/n98 https://files.magerun.net/n98-magerun2.phar && chmod +x /usr/local/bin/n98

# xdebug config
COPY conf/php/99-xdebug.ini /etc/php/8.3/fpm/conf.d/99-xdebug.ini
COPY conf/php/99-xdebug.ini /etc/php/8.3/cli/conf.d/99-xdebug.ini

# SSH known hosts for GitHub and Bitbucket
RUN mkdir -p ~/.ssh/
RUN curl -L https://api.github.com/meta | jq -r '.ssh_keys | .[]' | sed -e 's/^/github.com /' >> ~/.ssh/known_hosts
RUN curl https://bitbucket.org/site/ssh >> ~/.ssh/known_hosts

# configure mailhog
RUN apt update && apt install -y golang && go get github.com/mailhog/mhsendmail && apt -y remove golang && apt autoclean

RUN cp ~/go/bin/mhsendmail /usr/bin/mhsendmail
RUN echo 'sendmail_path ="mhsendmail --smtp-addr=127.0.0.1:1025"' >> /etc/php/8.3/fpm/php.ini
RUN echo 'sendmail_path ="mhsendmail --smtp-addr=127.0.0.1:1025"' >> /etc/php/8.3/cli/php.ini

# Node.js via nvm
ARG NODE_VERSION=--lts

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash && \
    export NVM_DIR="$HOME/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
    nvm install $NODE_VERSION && \
    nvm use $NODE_VERSION && \
    npm install -g npm@latest

ENV NODE_PATH $NVM_DIR/versions/node/$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/$NODE_VERSION/bin:$PATH

# gh CLI
RUN sudo mkdir -p -m 755 /etc/apt/keyrings \
	&& out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
	&& cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
	&& sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& sudo mkdir -p -m 755 /etc/apt/sources.list.d \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
	&& sudo apt update \
	&& sudo apt install gh -y && sudo apt clean

RUN echo 'export WORKSPACE_DIR=$(pwd)' >> /root/.bashrc
RUN echo '[ -f "$WORKSPACE_DIR/.env" ] && source "$WORKSPACE_DIR/.env"' >> /root/.bashrc
