#!/usr/bin/env bash
# Build a publishable devcontainer template artifact from this repo's working tree.
#
# Usage: ./.template/build.sh <output-dir>
#
# Produces: <output-dir>/magento/ — a directory ready for `devcontainer templates publish`.
#
# What it does:
#   1. Copies .devcontainer/ + supporting files from the working tree into <output-dir>/magento/.
#   2. Substitutes hardcoded version values with `${templateOption:*}` markers so end users
#      can override them at template-apply time.
#   3. Drops in devcontainer-template.json + README.md + NOTES.md from .template/.

set -euo pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <output-dir>" >&2
    exit 1
fi

OUT_DIR="$1"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TPL_DIR=".template"
TEMPLATE_ID="magento"

DST="$OUT_DIR/$TEMPLATE_ID"

rm -rf "$DST"
mkdir -p "$DST"

# Files and directories to ship as part of the template.
cp -a "$REPO_ROOT/.devcontainer" "$DST/.devcontainer"
cp -a "$REPO_ROOT/composer.json" "$DST/composer.json"
cp -a "$REPO_ROOT/justfile" "$DST/justfile"
cp -a "$REPO_ROOT/package.json" "$DST/package.json"
cp -a "$REPO_ROOT/.gitignore" "$DST/.gitignore"
cp -a "$REPO_ROOT/m2-hotfixes" "$DST/m2-hotfixes"

if [ -d "$REPO_ROOT/tests" ]; then
    cp -a "$REPO_ROOT/tests" "$DST/tests"
fi

if [ -d "$REPO_ROOT/.github" ]; then
    cp -a "$REPO_ROOT/.github" "$DST/.github"
    # The template doesn't ship its OWN publish workflow.
    rm -f "$DST/.github/workflows/publish-template.yml"
fi

# Templatize hardcoded values that should become user-facing options.
# Note: the working tree uses real values (php8.3, etc.) so it stays runnable;
# this step lifts those values into ${templateOption:*} markers in the artifact.
PHP_FILES=(
    "$DST/.devcontainer/Dockerfile-magento"
    "$DST/.devcontainer/.env"
)
for f in "${PHP_FILES[@]}"; do
    [ -f "$f" ] || continue
    sed -i \
        -e 's|php8\.3|php${templateOption:phpVersion}|g' \
        -e 's|/etc/php/8\.3|/etc/php/${templateOption:phpVersion}|g' \
        -e 's|php-fpm8\.3|php-fpm${templateOption:phpVersion}|g' \
        -e 's|^PHP_VERSION=8\.3$|PHP_VERSION=${templateOption:phpVersion}|' \
        -e 's|^COMPOSER_VERSION=latest-stable$|COMPOSER_VERSION=${templateOption:composerVersion}|' \
        "$f"
done

# Composer version: the option is currently advisory; the working tree pulls
# `latest-stable` and we don't pin it in the template either. To honor the
# option, end users can edit the `composer-installer | php --` line manually.

# Plumb commerceEdition into the bootstrap fallback.
COMMERCE_SH="$DST/.devcontainer/commerce.sh"
if [ -f "$COMMERCE_SH" ]; then
    sed -i 's|: ${COMMERCE_EDITION:="magento/project-community-edition"}|: ${COMMERCE_EDITION:="${templateOption:commerceEdition}"}|' "$COMMERCE_SH"
fi

# Drop in template manifest + docs.
cp "$REPO_ROOT/$TPL_DIR/devcontainer-template.json" "$DST/devcontainer-template.json"
cp "$REPO_ROOT/$TPL_DIR/NOTES.md" "$DST/NOTES.md"

# README is auto-generated by `devcontainer templates generate-docs` from manifest+NOTES.
# Generate it now so the published artifact has it.
if command -v devcontainer >/dev/null 2>&1; then
    devcontainer templates generate-docs -p "$OUT_DIR" >/dev/null
else
    echo "warning: devcontainer CLI not found; skipping README generation" >&2
fi

# Sanity-check: no unresolved templateOption markers should remain in fields that
# we explicitly handle. Anything else means the build script missed a substitution.
echo "=== Verifying templatization ==="
unresolved="$(grep -rn '8\.3' "$DST/.devcontainer/Dockerfile-magento" "$DST/.devcontainer/.env" 2>/dev/null | grep -v '\${templateOption' || true)"
if [ -n "$unresolved" ]; then
    echo "warning: hardcoded 8.3 still present:" >&2
    echo "$unresolved" >&2
fi

# Final sanity-check: the resulting devcontainer.json should be parseable, and
# (after default-substitution) docker compose config should validate.
python3 - <<PY
import json, sys
manifest = json.load(open("$DST/devcontainer-template.json"))
defaults = {k: v["default"] for k, v in manifest.get("options", {}).items()}
import re, pathlib
for f in pathlib.Path("$DST").rglob("*"):
    if not f.is_file(): continue
    try: text = f.read_text()
    except UnicodeDecodeError: continue
    leftover = re.findall(r"\\\${templateOption:[^}]+}", text)
    leftover = [m for m in leftover if m[len("\${templateOption:"):-1] not in defaults]
    if leftover:
        print(f"ERROR {f}: unknown templateOptions: {leftover}", file=sys.stderr)
        sys.exit(1)
print("Template manifest options match all referenced markers.")
PY

echo "Built template artifact at: $DST"
